version: '3'

services:
  db:
    image: mongo:latest # container image to be used
    restart: always
    ports: # expose ports in “host:container” format
      - 27017:27017
    environment: #env variables to pass into the container
      MONGODB_DATABASE: nest-course
